### ISSUE TITLE
Tip Radius Unnecessary

### ISSUE THREAD

**Issue by mohnjoosemiller** [nick-parker/Bread#1]
Tip Radius is an unnecessary complication of the config.txt file... This variable should be easily obtained from the nozzleD variable.

**Comment by nick-parker** [comment]
There are two motivations for keeping it separate at this time:
1. I'm not sure that the compensation actually has a positive impact on print quality, and varying the degree of compensation by lying about the radius is a nice diagnostic.
2. The measurement that actually matters is the radius of the tip of the nozzle - not the hole. This difference might be significant, I'm not sure. Refer back to 1 :P

**Comment by nick-parker** [comment]
If compensation turns out to be beneficial, we can set the default value of TipRadius to something like NozzleD*0.55.

The config file parsing is set up such that simply ommitting a setting will set it to its default value, so for "production" we could just leave this out of the default config.txt.

**Comment by mohnjoosemiller** [comment]
OOOHHHHH OK, I'm much more clear of what the variable is alluding to now...
Once I get more time, (and a chance to print with this), I'll make a README
for editing config.txt

Thanks for the clarification.
